# Docker-compose for Node.js backend

version: '3.8'
services:
  backend:
    image: 'node:lts-bullseye-slim'
    container_name: "backend"
    restart: unless-stopped
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "8081:8081"
    command: bash -c "npm install express axios && npm start"